# Site Settings

#google_analytics: UA-NNNNNNNN-N

title: v is for வலி
description: >- # this means to ignore newlines until "baseurl:"
  Repository for interdisciplinary, transgenre, interactive, digital, multimodal compositions, including my webtext dissertation, tiny games, and other audiovisual content.

header_pages:
  - index.md
  - about.md
  - gamedev.md
  - diss.md
  - pubs.md

footer: 'more at <a href="https://vyshalimanivannan.com/" target="_blank">வித்தியாசம்</a>'

style: dark # dark (default) or light
listen_for_clients_preferred_style: false # true or false (default)

plugins:
  - jekyll-seo-tag
