# Site Settings

#google_analytics: UA-NNNNNNNN-N

header_pages:
  - index.md
  - about.md

footer: '<a href="https://vyshalimanivannan.com/"><i class="fa-solid fa-globe"></i>personal website</a>'

style: dark # dark (default) or light
listen_for_clients_preferred_style: true # true or false (default)

plugins:
  - jekyll-seo-tag
