# Site Settings

#google_analytics: UA-NNNNNNNN-N

title: v is for வலி
description: >- # this means to ignore newlines until "baseurl:"
  Repository for interdisciplinary, transgenre, interactive, digital, multimodal compositions, including my webtext dissertation, tiny games, and other audiovisual content.

header_pages:
  - index.md
  - about.md
  - tinygames.md
  - selfhost.md
  - teaching.md 

footer: '/<a href="https://vyshalimanivannan.com/">website</a> /<a href="https://orcid.org/0000-0002-2853-0279">ORCID</a>'

style: dark # dark (default) or light
listen_for_clients_preferred_style: false # true or false (default)

plugins:
  - jekyll-seo-tag
