# Site Settings

#google_analytics: UA-NNNNNNNN-N

title: v is for வலி
# email: dlsite.com-83jd_p0.mold@alias.visforvali.com
description: >- # this means to ignore newlines until "baseurl:"
  Repository for interdisciplinary, transgenre, interactive, digital, multimodal compositions, including my webtext dissertation, tiny games, interactive narrative, and other audiovisual content.

header_pages:
  - index.md
  - about.md
  - tinygames.md
  - selfhost.md

footer: 'site at <a href="https://vyshalimanivannan.com/">வித்தியாசம்</a> /<a href="https://orcid.org/0000-0002-2853-0279">ORCID</a>'

style: dark # dark (default) or light
listen_for_clients_preferred_style: false # true or false (default)

plugins:
  - jekyll-seo-tag
