# Site Settings

#google_analytics: UA-NNNNNNNN-N

title: v is for வலி
description: >- # this means to ignore newlines until "baseurl:"
  Repository for interdisciplinary, transgenre, interactive, digital, multimodal compositions, including my webtext dissertation, tiny games, and other audiovisual content.

header_pages:
  - index.md
  - about.md
  - gamedev.md
  - pubs.md
  - diss.md

footer: 'read more on my <a href="https://vyshalimanivannan.com/">website</a>'

style: dark # dark (default) or light
listen_for_clients_preferred_style: false # true or false (default)

plugins:
  - jekyll-seo-tag
